- color: fef2c0
  description: Author 可申请锁住当前讨论
  name: Locked
- color: DD9D92
  description: ""
  name: AR
- color: 1A4156
  description: ""
  name: FPS
- color: 18D885
  description: ""
  name: MMO
- color: D767A8
  description: ""
  name: RPG
- color: B63DAF
  description: ""
  name: RTS
- color: 4E56FA
  description: ""
  name: VR
- color: 5D853C
  description: ""
  name: 图形学
- color: DB452A
  description: ""
  name: 市场
- color: A4882B
  description: ""
  name: 手游
- color: B9541A
  description: ""
  name: 测试
- color: 5319e7
  description: ""
  name: 游戏引擎
- color: 03AF09
  description: ""
  name: 游戏机制
- color: 8F54C2
  description: ""
  name: 游戏设计
- color: F0981E
  description: ""
  name: 物理学
- color: F2E1FE
  description: ""
  name: 音效
